name: weather_widget
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.1+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dart_style: ^2.3.6
  cupertino_icons: ^1.0.6
  get_it: ^7.6.7
  internet_connection_checker: ^1.0.0+1
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1
  freezed: ^2.4.7
  freezed_annotation: ^2.4.1
  flutter_bloc: ^8.1.5
  provider: ^6.1.2
  analyzer: ^6.4.1
  build_runner: ^2.4.8
  auto_route: ^8.0.0
  auto_route_generator: ^8.0.0
  meta: ^1.12.0
  equatable: ^2.0.5
  uuid: ^4.3.3
  path_provider: ^2.1.2
  window_manager: ^0.3.8
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  desktop_multi_window: ^0.2.0

dependency_overrides:
  meta: ^1.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
